apiVersion: v1
kind: Service
metadata:
  name: nokia-interview
  annotations:
          cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
          - protocol: TCP
            port: 80
            targetPort: 80
          - protocol: TCP
            port: 27017
            targetPort: 27017
          - protocol: TCP
            port: 8084
            targetPort: 8084            
  selector:
          app: nokia-interview

